[package]
name = "cargo-gdp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Cargo checks and narrow syntax diagnostics for Ghosts of Departed Proofs"
license.workspace = true
readme = "README.md"
repository.workspace = true

[dependencies]
serde_json.workspace = true
syn = { workspace = true, features = ["full", "parsing"] }
proc-macro2 = { workspace = true, features = ["span-locations"] }

[lints]
workspace = true
