[package]
name = "ghostproof-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Private nominal proof declarations for ghostproof"
license.workspace = true
readme = "README.md"
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full", "parsing", "printing", "clone-impls", "proc-macro"] }
proc-macro-crate = "=3.5.0"

[lints]
workspace = true
